### ISSUE TITLE
unable to register page as per README

### ISSUE THREAD

**Issue by wychoong** [ryangjchandler/filament-profile#17]
i followed the guide to add the following to service provider `boot` method
```php
            Filament::registerPages([
                \RyanChandler\FilamentProfile\Pages\Profile::class
            ]);
```

however i get route not defined error
so i dig further it appears to be in `mountNavigation` `getPages` is getting the correct pages array but in `route/web.php` `Filament::getPages()` is not getting the this page class

if I don't use the `registerPages` and register in `config/filament.php` `pages.register` key then everything works

```php
'pages' => [
        'register' => [
            Pages\Dashboard::class,
            \RyanChandler\FilamentProfile\Pages\Profile::class
        ],
    ],
```

**Comment by ryangjchandler** [comment]
@wychoong Can you try registering inside of the `register()` method instead?

**Comment by wychoong** [comment]
> @wychoong Can you try registering inside of the `register()` method instead?

this will cause all other filament's page/resource to be not registered

**Comment by ryangjchandler** [comment]
> > @wychoong Can you try registering inside of the `register()` method instead?
> 
> this will cause all other filament's page/resource to be not registered

Not sure I understand? Registering a single page in `register()` shouldn't prevent any other Filament features from working.

**Comment by wychoong** [comment]
yeah

so if I'm not registering anything yet, when i run route:list this is the result
![image](https://user-images.githubusercontent.com/67364036/183716806-0f902af9-f8f8-4e36-b32a-3fbcb08f0367.png)

register in `boot()`, you can see there are no changes in the routes
![image](https://user-images.githubusercontent.com/67364036/183717063-c45d7a06-62c4-45da-864d-39693a464e50.png)

however if I register in `register()`, Profile is available but the rest of Filament's pages/resources are gone
![image](https://user-images.githubusercontent.com/67364036/183717584-4fe14e27-0ed4-4b49-8fea-afc8e710293e.png)

if this helps
![image](https://user-images.githubusercontent.com/67364036/183718238-8ebb2ba6-c52e-42db-84f7-ac2e71ef17e2.png)

**Comment by ryangjchandler** [comment]
Hm, that sounds like a bug in Filament, not the package tbh.

**Comment by wychoong** [comment]
yeah, it was working for you right? do you have the version?

**Comment by wychoong** [comment]
will close this first, and use the workaround of setting in `config/filament.php`. if having the same issue in other project then maybe I'll create a repo to reproduce the issue.

**Comment by ryangjchandler** [comment]
@wychoong Or perhaps just update the README to use config instead.
